<?php

namespace Modules\Admin\Repositories;

use App\Models\Category;
use App\Models\SelectGroup;
use Illuminate\Http\Request;
use Modules\Core\Repositories\Api\BaseRepository;

class CategoryRepository extends BaseRepository
{

    public function getQuery()
    {
        $q = parent::getQuery(); // TODO: Change the autogenerated stub
        if(\request()->get('active'))
            return $q->where('is_active', 1);

        return $q;
    }

}
