<?php

namespace Modules\Admin\Repositories;

use App\Enums\ConstantEnum;
use App\Models\Category;
use App\Models\Feature;
use App\Models\Land;
use App\Models\LandBlock;
use Illuminate\Http\Request;
use Modules\Core\Repositories\Api\BaseRepository;
use Modules\Core\Repositories\FileRepository;
use function PHPUnit\Framework\isEmpty;

class EmployeeRepository extends BaseRepository
{
    public function saving($model, Request $request)
    {
        $model->services()->sync($request->service_id);
        return parent::saving($model, $request); // TODO: Change the autogenerated stub
    }

}
