<?php

namespace Modules\Admin\Repositories;

use App\Enums\ConstantEnum;
use App\Models\Category;
use App\Models\Feature;
use App\Models\Land;
use App\Models\LandBlock;
use Illuminate\Http\Request;
use Modules\Core\Repositories\Api\BaseRepository;
use Modules\Core\Repositories\FileRepository;
use function PHPUnit\Framework\isEmpty;

class ServiceRepository extends BaseRepository
{
    protected function getAttributes(Request $request)
    {
        $data = parent::getAttributes($request); // TODO: Change the autogenerated stub

        $data['category_data'] = Category::find($request->category_id) ?? [];

        return $data;
    }
}
