<?php

namespace Modules\Admin\Repositories;

use App\Models\Category;
use App\Models\SelectGroup;
use Illuminate\Http\Request;
use Modules\Core\Repositories\Api\BaseRepository;

class ServiceRepository extends BaseRepository
{

    public function saving($model, Request $request)
    {

        SelectGroup::whereIn('id', pluck($request->select_group, 'id'))->update([
            'service_id' => $model->id
        ]);

        return parent::saving($model, $request); // TODO: Change the autogenerated stub
    }

}
