<?php


namespace Modules\Admin\Http\Resources;

use Illuminate\Support\Facades\Hash;
use Modules\Core\Http\Resources\BaseResource;
use App\Models\Admin;

class AdminsResource extends BaseResource

{
    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request
     * @return array
     */
    public function toArray($request)
    {
       $role= $this->roles()->first();
        dd($this->roles);
        return [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'image_url' => $this->avatar ? image_url($this->avatar) : null,
            'role' => optional($role)->id,
            'is_active' => $this->is_active,
            'role_name' => optional($role)->name,
        ];
    }
    public function serializeForEdit($request)
    {

        return array_merge($this->toArray($request), [
            'user_name' => $this->getLocale($this->name),
            'policies' => $this->encodedPermissions() ?? [],
        ]); // TODO: Change the autogenerated stub
    }

}
