<?php


namespace Permissions\Resources;

use Modules\Core\Http\Resources\BaseResource;

class RoleResource extends BaseResource
{
    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function toArray($request)
    {
        return array_merge([
            'id' => $this->id,
            'name' => $this->name,
        ], $this->serializeForExcel());
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function serializeForEdit($request)
    {

        return array_merge($this->toArray($request), [
            // Fix When edit an empty Permission not save
            'permissions' => count($this->fetchPermissions()) ? $this->fetchPermissions() : (object)null
        ]); // TODO: Change the autogenerated stub
    }

    public function serializeForExcel()
    {
        $permissions = [];
        foreach ($this->fetchPermissions() as $key => $permission) {
            $permission_ = collect($permission)->map(function ($value) {
                return trans("admin::lang.$value");
            })->toArray();
            $permissions[$key] = implode(',', $permission_);
        }
        return $permissions;
    }

    public function fetchPermissions()
    {
        $permissions = [];
        foreach ($this->permissions->pluck('name') as $item) {
            $exploded = explode('.', $item);
            $permissions[$exploded[0]][] = $exploded[1];
        }
        return $permissions;
    }
}
