<?php

namespace Modules\Admin\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Modules\Core\Http\Requests\BaseRequest;

class CategoryRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name.ar' => 'required|max:255',
            'name.en' => 'required|max:255',
            'description.ar' => 'required|max:255',
            'description.en' => 'required|max:255',
            'is_active' => 'required|in:0,1'
        ];
    }

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function messages()
    {
        return [
            'name.ar.required' => trans('admin::messages.name_ar_required'),
            'name.en.required' => trans('admin::messages.name_en_required'),
            'description.ar.required' => trans('admin::messages.description_ar_required'),
            'description.en.required' => trans('admin::messages.description_en_required'),
        ]; // TODO: Change the autogenerated stub
    }
}
