<?php

namespace Modules\Admin\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Modules\Core\Http\Requests\BaseRequest;

class EmployeeRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|max:255',
            'email' => ['required', 'max:255', Rule::unique('employees', 'email')->ignore(request()->get('id'))],
            'mobile' => ['required', 'max:10', Rule::unique('employees', 'mobile')->ignore(request()->get('id'))],
            'commission' => request()->get('company_id') ? 'nullable' : 'required',
            'password' => request()->routeIs('employee.store') ? 'required|max:255' : '',
            'company_id' => ['nullable', 'exists:companies,id'],
            'service_id' => 'required',
        ];
    }

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function messages()
    {
        return [
            'name.required' => trans('admin::messages.name_required'),
            'commission.required' => trans('admin::messages.commission_required'),
        ]; // TODO: Change the autogenerated stub
    }
}
