<?php

namespace Modules\Admin\Http\Requests;

use App\Enum\ConstantEnum;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Modules\Core\Http\Requests\BaseRequest;

class SectionRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name.ar' => 'required|max:255',
            'name.en' => 'required|max:255',
            'categories' => request()->get('type') === 'category_section' ? 'required' : 'nullable',
            'services' => request()->get('type') === 'service_section' ? 'required' : 'nullable',
            'images' => request()->get('type') === 'slider_section' ? 'required' : 'nullable',
        ];
    }

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function messages()
    {
        return [
            'name.ar.required' => trans('admin::messages.name_ar_required'),
            'name.en.required' => trans('admin::messages.name_en_required'),
            'categories.required' => trans('admin::messages.categories_required'),
            'services.required' => trans('admin::messages.categories_required'),
            'images.required' =>  trans('admin::messages.images_required'),
        ]; // TODO: Change the autogenerated stub
    }
}
