<?php

namespace Modules\Customer\Repositories;

use App\Models\Customer;
use App\Models\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Modules\Core\Repositories\Api\BaseRepository;
use Modules\Customer\Exceptions\OrderException;

class OrderRepository extends BaseRepository
{
    protected function getAttributes(Request $request)
    {
        $data = parent::getAttributes($request); // TODO: Change the autogenerated stub
        $service = Service::find($request->service_id);
        $data['customer_id'] = userAuth()->id;
        $data['customer_data'] = userAuth();
        $data['service_data'] = $service;
        return $data;
    }

    public function store(Request $request)
    {
        DB::beginTransaction();
        try {
            $model = parent::store($request);
            DB::commit();
            return $model;
        } catch (OrderException $orderException) {
            DB::rollback();
            throw $orderException;
        }
    }
}
